---
title: "LMISDQSyntax"
author: "Vas"
date: '2022-07-06'
output: html_document
---
```{r echo=FALSE, warning=FALSE, message=FALSE}
#Loading the packages to work with
library(semTools)
library(haven)
library(semPlot)
library(lavaan)
library (psych)
library (psychTools)
library(tidyverse)
library (SBSDiff)
library (esem)


```

Loasd the Data
```{r}
data<-read_sav("data.sav")
data<-data%>%select(-hicid)
data1<-data%>%select(ends_with("_1"))
data2<-data%>%select(ends_with("_2"))
data3<-data%>%select(ends_with("_3"))

```
ESEM Step1a
```{r}
main_loadings_list <- list(
  pp = c("s6_1", "s11_1", "s14_1", "s19_1", "s23_1"),
  cp = c("s5_1", "s7_1", "s12_1", "s18_1", "s22_1"),
  es = c("s3_1", "s8_1", "s13_1", "s16_1", "s24_1"),
  ha = c("s2_1","s10_1","s15_1","s21_1","s25_1"),
  ps = c("s1_1","s4_1","s9_1","s17_1","s20_1")
)
target<-make_target(
           data=data1, 
           keys=main_loadings_list)

esem_efa_results<-esem_efa(
     data=data1,
     nfactors = 5,
     rotate="TargetQ",
    Target= target)

esem_efa_results$loadings

fa.diagram(esem_efa_results) 

referent_list <- create_referent(esem_efa_results)

esem_model <- esem_syntax(esem_efa_results, referent_list)


writeLines(esem_model)

esem_fit <- esem_cfa(model=esem_model, 
                data=data1, 
          



                std.lv=TRUE,




                ordered = TRUE)

summary(esem_fit, fit.measures = TRUE, standardized = TRUE, ci = TRUE)


```





```{r echo=FALSE, warning=FALSE, message=FALSE}
#Run the EFA/ESEM model at time point 1

esem_efa_results1 <- esem_efa(data1, 
                      nfactors =5,
                      fm = 'ML',
                      rotate="geominT", 
                      scores="regression", 
                      residuals=TRUE, 
                      missing=TRUE)
```

```{r}
esem_model1 <- esem_syntax(esem_efa_results1, referent_list)

writeLines(esem_model1)
```


```{r}
#To test the model
SDQ.fit.1 <- cfa(esem_model1, data1, estimator="WLSMV", meanstructure=F)
summary(SDQ.fit.1, standardized = T, fit.measures = T, rsq = T)
```

Reliability

```{r}
semTools::reliability(SDQ.fit.1)
```

```{r}
modindices(SDQ.fit.1,sort.=TRUE)
```

```{r}
semPaths(SDQ.fit.1, whatLabels = "std", layout = "tree2", rotation = 2, sizeLat = 12, sizeInt = 5, sizeMan2 = 5, shapeMan = "square", shapeLat = "circle",node.width = 0.6, asize = 3, edge.label.cex = 0.75, fade = F)

```

EFA ESEM model 2
```{r echo=FALSE, warning=FALSE, message=FALSE}
esem_efa_results2 <- esem_efa(data2, 
                      nfactors =5,
                      fm = 'ML',
                      rotate="geominT", 
                      scores="regression", 
                      residuals=TRUE, 
                      missing=TRUE)
```


```{r}
esem_model2 <- esem_syntax(esem_efa_results2, referent_list)

writeLines(esem_model2)
```

```{r}
SDQ.fit.2 <- cfa(esem_model2, data2, estimator="WLSMV", meanstructure=F)
summary(SDQ.fit.2, standardized = T, fit.measures = T, rsq = T)
```


```{r}
semTools::reliability(SDQ.fit.2)
```

Modindices
```{r}
modindices(SDQ.fit.2,sort.=TRUE)
```
Plot the SDQ2 Fit
```{r}
semPaths(SDQ.fit.2, whatLabels = "std", layout = "tree2", rotation = 2, sizeLat = 12, sizeInt = 5, sizeMan2 = 5, shapeMan = "square", shapeLat = "circle",node.width = 0.6, asize = 3, edge.label.cex = 0.75, fade = F)

```
```{r}
# Calculate EFA ESEM model 3

esem_efa_results3 <- esem_efa(data3, 
                      nfactors =5,
                      fm = 'ML',
                      rotate="geominT", 
                      scores="regression", 
                      residuals=TRUE, 
                      missing=TRUE)

```
Write ESEM Model 3
```{r}
esem_model3 <- esem_syntax(esem_efa_results3, referent_list)

writeLines(esem_model3)
```
Test the ESEM Model 3
```{r}
SDQ.fit.3 <- cfa(esem_model3, data3, estimator="WLSMV", meanstructure=F)
summary(SDQ.fit.3, standardized = T, fit.measures = T, rsq = T)
```

Reliabilities 3 and modindices 3
```{r}
semTools::reliability(SDQ.fit.3)
modindices(SDQ.fit.3,sort.=TRUE)
```
Plot ESEM 3
```{r}
semPaths(SDQ.fit.3, whatLabels = "std", layout = "tree2", rotation = 2, sizeLat = 12, sizeInt = 5, sizeMan2 = 5, shapeMan = "square", shapeLat = "circle",node.width = 0.6, asize = 3, edge.label.cex = 0.75, fade = F)
```



```{r}
#Introducing Configural model
#ESEM_MODEL_LMI<-paste0(esem_model1,esem_model2,esem_model3, collapse = "/n")
ESEM_CONF<-"ML11=~start(-0.10181813334364)*s1_1+
 0.341021830091293*s2_1+
 start(0.475689597452262)*s3_1+
 start(0.0448498091001827)*s4_1+
 start(0.532706326072059)*s5_1+
 start(0.380270886458239)*s6_1+
 -0.17677526014272*s7_1+
 0.557302560480769*s8_1+
 0.0154555580721658*s9_1+
 start(0.445591230767454)*s10_1+
 start(-0.14715624332716)*s11_1+
 start(0.295375297579211)*s12_1+
 0.640790531584111*s13_1+
 start(-0.283662392937637)*s14_1+
 start(0.496315161517282)*s15_1+
 start(0.456119066758138)*s16_1+
 start(-0.0300724138783131)*s17_1+
 start(0.52803060716866)*s18_1+
 start(0.545878451941098)*s19_1+
 start(0.0643676895943769)*s20_1+
 start(-0.166911003348391)*s21_1+
 start(0.218792089074707)*s22_1+
 start(0.378607161220922)*s23_1+
 start(0.45936304785388)*s24_1+
 start(-0.245500790144707)*s25_1
 
 ML21=~start(0.46952646970973)*s1_1+
 -0.168321479151942*s2_1+
 start(-0.0305336785896823)*s3_1+
 start(0.191527842910332)*s4_1+
 start(-0.208955192240166)*s5_1+
 start(0.00683175598992413)*s6_1+
 0.555747675045059*s7_1+
 0.106642278912651*s8_1+
 0.481947375866067*s9_1+
 start(-0.109566114954949)*s10_1+
 start(0.124527511539424)*s11_1+
 start(-0.209573540829713)*s12_1+
 -0.0361459663233181*s13_1+
 start(0.169377089517239)*s14_1+
 start(-0.342744908740705)*s15_1+
 start(-0.0619016727264182)*s16_1+
 start(0.394776044259853)*s17_1+
 start(-0.249105043255145)*s18_1+
 start(0.0445460428700227)*s19_1+
 start(0.505876999620719)*s20_1+
 start(0.514549905298726)*s21_1+
 start(-0.14936737709603)*s22_1+
 start(0.118209802834279)*s23_1+
 start(0.0809241962896773)*s24_1+
 start(0.550687205664788)*s25_1
 
 ML31=~start(0.0318685617912012)*s1_1+
 0.630374964766479*s2_1+
 start(0.0571887154094396)*s3_1+
 start(0.0538030402265071)*s4_1+
 start(0.0637918865107856)*s5_1+
 start(0.0037595073842555)*s6_1+
 -0.0295740847687255*s7_1+
 0.0144582068998616*s8_1+
 0.0306795597767665*s9_1+
 start(0.621109426134197)*s10_1+
 start(0.0769751334597619)*s11_1+
 start(0.0197092215986661)*s12_1+
 -0.0918814679617119*s13_1+
 start(0.029978222084595)*s14_1+
 start(0.312265122107737)*s15_1+
 start(0.0138061871093199)*s16_1+
 start(-0.0351187831077965)*s17_1+
 start(0.022985389287828)*s18_1+
 start(-0.0640748105499755)*s19_1+
 start(-0.0526278002086372)*s20_1+
 start(-0.126916795352038)*s21_1+
 start(0.00435500098796124)*s22_1+
 start(-0.0321217727857697)*s23_1+
 start(-0.0032698720232859)*s24_1+
 start(-0.134427464376022)*s25_1
 
 ML41=~start(0.117843205299031)*s1_1+
 0.00848371228260159*s2_1+
 start(0.0929136307518985)*s3_1+
 start(-0.0123382758875751)*s4_1+
 start(-0.0558123167628648)*s5_1+
 start(0.023775361078292)*s6_1+
 0.0952557898945923*s7_1+
 0.369217144239234*s8_1+
 0.0114539033227634*s9_1+
 start(-0.00371410479131914)*s10_1+
 start(-0.00729073815554198)*s11_1+
 start(-0.15945379876267)*s12_1+
 0.0209243770588006*s13_1+
 start(-0.0610717599897765)*s14_1+
 start(0.013669520843305)*s15_1+
 start(0.359777064992566)*s16_1+
 start(0.0236008838623919)*s17_1+
 start(-0.206663442278027)*s18_1+
 start(-0.138933495767261)*s19_1+
 start(-0.154035310918099)*s20_1+
 start(0.00469705937706368)*s21_1+
 start(-0.189076897903099)*s22_1+
 start(-0.0695111074225318)*s23_1+
 start(0.286447769550499)*s24_1+
 start(-0.0600228848907743)*s25_1
 
 ML51=~start(0.386993546331018)*s1_1+
 0.0209490404099033*s2_1+
 start(-0.0054433991686893)*s3_1+
 start(0.326516136546854)*s4_1+
 start(-0.0250259504849937)*s5_1+
 start(-0.27989807565512)*s6_1+
 0.0151065500711747*s7_1+
 -0.0231256595924317*s8_1+
 0.425339658015609*s9_1+
 start(0.0174598806360039)*s10_1+
 start(0.32635887160996)*s11_1+
 start(-0.0271979194024951)*s12_1+
 -0.082431747549817*s13_1+
 start(0.402026051871148)*s14_1+
 start(0.115151805310133)*s15_1+
 start(0.0441996218569334)*s16_1+
 start(0.353082490590944)*s17_1+
 start(-0.0219255651364234)*s18_1+
 start(-0.166325529041567)*s19_1+
 start(0.167267894714794)*s20_1+
 start(0.0475302921193128)*s21_1+
 start(-0.0102300226444448)*s22_1+
 start(-0.215432585452835)*s23_1+
 start(0.00968333520180835)*s24_1+
 start(-0.0288085462659386)*s25_1

ML12=~start(-0.10181813334364)*s1_2+
 0.341021830091293*s2_2+
 start(0.475689597452262)*s3_2+
 start(0.0448498091001827)*s4_2+
 start(0.532706326072059)*s5_2+
 start(0.380270886458239)*s6_2+
 -0.17677526014272*s7_2+
 0.557302560480769*s8_2+
 0.0154555580721658*s9_2+
 start(0.445591230767454)*s10_2+
 start(-0.14715624332716)*s11_2+
 start(0.295375297579211)*s12_2+
 0.640790531584111*s13_2+
 start(-0.283662392937637)*s14_2+
 start(0.496315161517282)*s15_2+
 start(0.456119066758138)*s16_2+
 start(-0.0300724138783131)*s17_2+
 start(0.52803060716866)*s18_2+
 start(0.545878451941098)*s19_2+
 start(0.0643676895943769)*s20_2+
 start(-0.166911003348391)*s21_2+
 start(0.218792089074707)*s22_2+
 start(0.378607161220922)*s23_2+
 start(0.45936304785388)*s24_2+
 start(-0.245500790144707)*s25_2
 
 ML22=~start(0.46952646970973)*s1_2+
 -0.168321479151942*s2_2+
 start(-0.0305336785896823)*s3_2+
 start(0.191527842910332)*s4_2+
 start(-0.208955192240166)*s5_2+
 start(0.00683175598992413)*s6_2+
 0.555747675045059*s7_2+
 0.106642278912651*s8_2+
 0.481947375866067*s9_2+
 start(-0.109566114954949)*s10_2+
 start(0.124527511539424)*s11_2+
 start(-0.209573540829713)*s12_2+
 -0.0361459663233181*s13_2+
 start(0.169377089517239)*s14_2+
 start(-0.342744908740705)*s15_2+
 start(-0.0619016727264182)*s16_2+
 start(0.394776044259853)*s17_2+
 start(-0.249105043255145)*s18_2+
 start(0.0445460428700227)*s19_2+
 start(0.505876999620719)*s20_2+
 start(0.514549905298726)*s21_2+
 start(-0.14936737709603)*s22_2+
 start(0.118209802834279)*s23_2+
 start(0.0809241962896773)*s24_2+
 start(0.550687205664788)*s25_2
 
 ML32=~start(0.0318685617912012)*s1_2+
 0.630374964766479*s2_2+
 start(0.0571887154094396)*s3_2+
 start(0.0538030402265071)*s4_2+
 start(0.0637918865107856)*s5_2+
 start(0.0037595073842555)*s6_2+
 -0.0295740847687255*s7_2+
 0.0144582068998616*s8_2+
 0.0306795597767665*s9_2+
 start(0.621109426134197)*s10_2+
 start(0.0769751334597619)*s11_2+
 start(0.0197092215986661)*s12_2+
 -0.0918814679617119*s13_2+
 start(0.029978222084595)*s14_2+
 start(0.312265122107737)*s15_2+
 start(0.0138061871093199)*s16_2+
 start(-0.0351187831077965)*s17_2+
 start(0.022985389287828)*s18_2+
 start(-0.0640748105499755)*s19_2+
 start(-0.0526278002086372)*s20_2+
 start(-0.126916795352038)*s21_2+
 start(0.00435500098796124)*s22_2+
 start(-0.0321217727857697)*s23_2+
 start(-0.0032698720232859)*s24_2+
 start(-0.134427464376022)*s25_2
 
 ML42=~start(0.117843205299031)*s1_2+
 0.00848371228260159*s2_2+
 start(0.0929136307518985)*s3_2+
 start(-0.0123382758875751)*s4_2+
 start(-0.0558123167628648)*s5_2+
 start(0.023775361078292)*s6_2+
 0.0952557898945923*s7_2+
 0.369217144239234*s8_2+
 0.0114539033227634*s9_2+
 start(-0.00371410479131914)*s10_2+
 start(-0.00729073815554198)*s11_2+
 start(-0.15945379876267)*s12_2+
 0.0209243770588006*s13_2+
 start(-0.0610717599897765)*s14_2+
 start(0.013669520843305)*s15_2+
 start(0.359777064992566)*s16_2+
 start(0.0236008838623919)*s17_2+
 start(-0.206663442278027)*s18_2+
 start(-0.138933495767261)*s19_2+
 start(-0.154035310918099)*s20_2+
 start(0.00469705937706368)*s21_2+
 start(-0.189076897903099)*s22_2+
 start(-0.0695111074225318)*s23_2+
 start(0.286447769550499)*s24_2+
 start(-0.0600228848907743)*s25_2
 
 ML52=~start(0.386993546331018)*s1_2+
 0.0209490404099033*s2_2+
 start(-0.0054433991686893)*s3_2+
 start(0.326516136546854)*s4_2+
 start(-0.0250259504849937)*s5_2+
 start(-0.27989807565512)*s6_2+
 0.0151065500711747*s7_2+
 -0.0231256595924317*s8_2+
 0.425339658015609*s9_2+
 start(0.0174598806360039)*s10_2+
 start(0.32635887160996)*s11_2+
 start(-0.0271979194024951)*s12_2+
 -0.082431747549817*s13_2+
 start(0.402026051871148)*s14_2+
 start(0.115151805310133)*s15_2+
 start(0.0441996218569334)*s16_2+
 start(0.353082490590944)*s17_2+
 start(-0.0219255651364234)*s18_2+
 start(-0.166325529041567)*s19_2+
 start(0.167267894714794)*s20_2+
 start(0.0475302921193128)*s21_2+
 start(-0.0102300226444448)*s22_2+
 start(-0.215432585452835)*s23_2+
 start(0.00968333520180835)*s24_2+
 start(-0.0288085462659386)*s25_2
ML13=~start(-0.10181813334364)*s1_3+
 0.341021830091293*s2_3+
 start(0.475689597452262)*s3_3+
 start(0.0448498091001827)*s4_3+
 start(0.532706326072059)*s5_3+
 start(0.380270886458239)*s6_3+
 -0.17677526014272*s7_3+
 0.557302560480769*s8_3+
 0.0154555580721658*s9_3+
 start(0.445591230767454)*s10_3+
 start(-0.14715624332716)*s11_3+
 start(0.295375297579211)*s12_3+
 0.640790531584111*s13_3+
 start(-0.283662392937637)*s14_3+
 start(0.496315161517282)*s15_3+
 start(0.456119066758138)*s16_3+
 start(-0.0300724138783131)*s17_3+
 start(0.52803060716866)*s18_3+
 start(0.545878451941098)*s19_3+
 start(0.0643676895943769)*s20_3+
 start(-0.166911003348391)*s21_3+
 start(0.218792089074707)*s22_3+
 start(0.378607161220922)*s23_3+
 start(0.45936304785388)*s24_3+
 start(-0.245500790144707)*s25_3
 
 ML23=~start(0.46952646970973)*s1_3+
 -0.168321479151942*s2_3+
 start(-0.0305336785896823)*s3_3+
 start(0.191527842910332)*s4_3+
 start(-0.208955192240166)*s5_3+
 start(0.00683175598992413)*s6_3+
 0.555747675045059*s7_3+
 0.106642278912651*s8_3+
 0.481947375866067*s9_3+
 start(-0.109566114954949)*s10_3+
 start(0.124527511539424)*s11_3+
 start(-0.209573540829713)*s12_3+
 -0.0361459663233181*s13_3+
 start(0.169377089517239)*s14_3+
 start(-0.342744908740705)*s15_3+
 start(-0.0619016727264182)*s16_3+
 start(0.394776044259853)*s17_3+
 start(-0.249105043255145)*s18_3+
 start(0.0445460428700227)*s19_3+
 start(0.505876999620719)*s20_3+
 start(0.514549905298726)*s21_3+
 start(-0.14936737709603)*s22_3+
 start(0.118209802834279)*s23_3+
 start(0.0809241962896773)*s24_3+
 start(0.550687205664788)*s25_3
 
 ML33=~start(0.0318685617912012)*s1_3+
 0.630374964766479*s2_3+
 start(0.0571887154094396)*s3_3+
 start(0.0538030402265071)*s4_3+
 start(0.0637918865107856)*s5_3+
 start(0.0037595073842555)*s6_3+
 -0.0295740847687255*s7_3+
 0.0144582068998616*s8_3+
 0.0306795597767665*s9_3+
 start(0.621109426134197)*s10_3+
 start(0.0769751334597619)*s11_3+
 start(0.0197092215986661)*s12_3+
 -0.0918814679617119*s13_3+
 start(0.029978222084595)*s14_3+
 start(0.312265122107737)*s15_3+
 start(0.0138061871093199)*s16_3+
 start(-0.0351187831077965)*s17_3+
 start(0.022985389287828)*s18_3+
 start(-0.0640748105499755)*s19_3+
 start(-0.0526278002086372)*s20_3+
 start(-0.126916795352038)*s21_3+
 start(0.00435500098796124)*s22_3+
 start(-0.0321217727857697)*s23_3+
 start(-0.0032698720232859)*s24_3+
 start(-0.134427464376022)*s25_3
 
 ML43=~start(0.117843205299031)*s1_3+
 0.00848371228260159*s2_3+
 start(0.0929136307518985)*s3_3+
 start(-0.0123382758875751)*s4_3+
 start(-0.0558123167628648)*s5_3+
 start(0.023775361078292)*s6_3+
 0.0952557898945923*s7_3+
 0.369217144239234*s8_3+
 0.0114539033227634*s9_3+
 start(-0.00371410479131914)*s10_3+
 start(-0.00729073815554198)*s11_3+
 start(-0.15945379876267)*s12_3+
 0.0209243770588006*s13_3+
 start(-0.0610717599897765)*s14_3+
 start(0.013669520843305)*s15_3+
 start(0.359777064992566)*s16_3+
 start(0.0236008838623919)*s17_3+
 start(-0.206663442278027)*s18_3+
 start(-0.138933495767261)*s19_3+
 start(-0.154035310918099)*s20_3+
 start(0.00469705937706368)*s21_3+
 start(-0.189076897903099)*s22_3+
 start(-0.0695111074225318)*s23_3+
 start(0.286447769550499)*s24_3+
 start(-0.0600228848907743)*s25_3
 
 ML53=~start(0.386993546331018)*s1_3+
 0.0209490404099033*s2_3+
 start(-0.0054433991686893)*s3_3+
 start(0.326516136546854)*s4_3+
 start(-0.0250259504849937)*s5_3+
 start(-0.27989807565512)*s6_3+
 0.0151065500711747*s7_3+
 -0.0231256595924317*s8_3+
 0.425339658015609*s9_3+
 start(0.0174598806360039)*s10_3+
 start(0.32635887160996)*s11_3+
 start(-0.0271979194024951)*s12_3+
 -0.082431747549817*s13_3+
 start(0.402026051871148)*s14_3+
 start(0.115151805310133)*s15_3+
 start(0.0441996218569334)*s16_3+
 start(0.353082490590944)*s17_3+
 start(-0.0219255651364234)*s18_3+
 start(-0.166325529041567)*s19_3+
 start(0.167267894714794)*s20_3+
 start(0.0475302921193128)*s21_3+
 start(-0.0102300226444448)*s22_3+
 start(-0.215432585452835)*s23_3+
 start(0.00968333520180835)*s24_3+
 start(-0.0288085462659386)*s25_3"


#writeLines(ESEM_MODEL_LMI)
```

#Test the model:
```{r}
#SDQ.fit.LMI <- cfa(ESEM_CONF, data, estimator="MLR", meanstructure=F)
#summary(SDQ.fit.LMI, standardized = T, fit.measures = T, rsq = T)
```

```{r}
#ESEM_Metric<-""
```

